
export const keywords = [
  "energy-efficient",
  "energy efficiency",
  "circular economy",
  "ecological",
  "eco-",
  "to nature",
  "from nature",
  "the nature",
  "of nature",
  "with nature",
  "community health",
  "integrated care",
  "telehealth",
  "health education",
  "eco-minded",
  "sustainable living",
  "sustainable development",
  "sustainable community",
  "sustainable lifestyle",
  "sustainable practices",
  "sustainable solutions",
  "sustainable design",
  "sustainable energy",
  "eco-conscious", 
  "eco-friendly",
  "carbon",
  "responsible resource",
  "farming",
  "green",
  "eco-friendly",
  "the environment",
  "environmental",
  "climate",
  "global warming",
  "climate change",
  "climate action",
  "carbon reduction",
  "emissions",
  "renewables",
  "mental health",
  "mental wellbeing",
  "cultural wellbeing",
  "global wellbeing",
  "societal wellbeing",
  "society",
  "wellness",
  "emotional support",
  "psychological",
  "counseling",
  "therapy",
  "behavioral health",
  "animals",
  "animal welfare",
  "wildlife",
  "conservation",
  "biodiversity",
  "species protection",
  "habitat",
  "endangered species",
  "grades",
  "special ed",
  "autism",
  "disorder",
  "education for",
  "curriculum",
  "educational",
  "teaches",
  "teach them",
  "student",
  "child development",
  "global development",
  "international aid",
  "foreign aid",
  "poverty alleviation",
  "humanitarian",
  "relief",
  "disinformation",
  "misinformation",
  "truth",
  "fact-checking",
  "media literacy",
  "fake news",
  "information integrity",
  "social work",
  "outreach",
  "community building",
  "community outreach",
  "local communit",
  "support communit",
  "underrepresented",
  "marginalized",
  "justice reform",
  "energy reform",
  "social safety",
  "safety net",
  "inclusive education",
  "education access",
  "childhood education",
  "literacy program",
  "vulnerable",
  "underserved",
  "disadvantaged",
  "impoverished",
  "social services",
  "grassroots",
  "food",
  "nutrition",
  "hunger",
  "feeding",
  "food security",
  "agriculture",
  "farming",
  "organic",
  "shelter",
  "homelessness",
  "homeless",
  "transitional housing",
  "affordable housing",
  "+ community",
  "LGBTQ community",
  "LGBTQIA community",
  "youth",
  "children",
  "adolescents",
  "teenagers",
  "kids",
  "young people",
  "queer",
  "non-binary",
  "transgender",
  "non-profit",
  "NGO",
  "charity",
  "volunteer",
  "human rights",
  "civil rights",
  "advocacy",
  "activism",
  "renewable energy",
  "clean energy",
  "solar",
  "wind energy",
  "wind technology",
  "wind power",
  "wind turbine",
  "wind farm",
  "hydro",
  "geothermal",
  "biomass",
  "energy efficiency",
  "decarbonization",
  "clean water",
  "water access",
  "sanitation",
  "hygiene",
  "water security",
  "safe water",
  "accessible food",
  "food access",
  "accessible climate",
  "accessible energy",
  "accessible healthcare",
  "accessible education",
  "accessible housing",
  "accessible transportation",
  "accessible psych",
  "accessible legal",
  "accessible law",
  "accessible justice",
  "wastewater",
  "water purification",
  "healthcare access",
  "access to healthcare",
  "healthcare equity",
  "healthcare for",
  "healthcare services",
  "healthcare providers",
  "healthcare professionals",
  "healthcare workers",
  "of healthcare",
  "healthcare system",
  "healthcare industry",
  "mecical needs",
  "medical treatment",
  "medical services",
  "medicine",
  "medical care",
  "public health",
  "medical services",
  "clinics",
  "hospitals",
  "ethical",
  "fair trade",
  "fair wage",
  "responsible sourcing",
  "social responsibility",
  "CSR",
  "addict",
  "recovery",
  "rehabilitation",
  "substance abuse",
  "mental health",
  "trauma",
  "PTSD",
  "counseling",
  "indigenous",
  "native rights",
  "aboriginal",
  "tribal",
  "First Nations",
  "trafficking",
  "human trafficking",
  "exploitation",
  "slavery",
  "forced labor",
  "justice",
  "legal aid",
  "restorative justice",
  "criminal justice reform",
  "low-income housing",
  "subsidized housing",
  "malnutrition",
  "food justice",
  "legal services",
  "from the law",
  "with the law",
  ", law",
  "access to law",
  "educated in law",
  "disease prevention",
  "vaccination",
  "health education",
  "social justice",
  "community empowerment",
  "grassroots org",
  "grassroots movement",
  "social equity",
  "civil rights",
  "disaster relief",
  "emergency response",
  "crisis management",
  "humanitarian aid",
  "ethical trade",
  "fair labor",
  "gender equality",
  "women's rights",
  "gender equity",
  "empowerment",
  "gender-based violence",
  "refugee",
  "asylum",
  "immigrant",
  "immigration",
  "migrant",
  "refugee support",
  "immigrant rights",
  "preservation",
  "urban planning",
  "city planning",
  "sustainable cities",
  "green building",
  "public transportation",
  "ethical tech",
  "responsible AI",
  "data privacy",
  "cybersecurity",
  "vocational",
  "dairy",
  "meat",
  "vegan",
  "vegetarian",
  "vegetable",
  "special needs",
  "affordable education",
  "education for all",
  "literacy",
  "wildlife",
  "species protection",
  "ecology",
  "public policy",
  "government",
  "policy reform",
  "international development",
  "poverty alleviation",
  "economic development",
  "social impact",
  "clean water",
  "safe drinking water",
  "for good",
  "help people",
  "help anyone",
  "help children",
  "help families",
  "help animals",
  "help communities",
  "help the environment",
  "help the planet",
  "help the world",
  "help society",
];